# Generated by Django 4.0.6 on 2023-01-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('price', models.CharField(max_length=30, verbose_name='Цена')),
                ('release_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода')),
                ('lte_exists', models.CharField(default=True, max_length=200, verbose_name='LTE')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
    ]
