# Generated by Django 4.0.6 on 2022-10-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('release_date', models.DateTimeField()),
                ('lte_exists', models.CharField(default=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
    ]
