# Generated by Django 4.0.6 on 2023-01-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
